name = "bertho-ai"
main = "src/index.js"
compatibility_date = "2026-08-20"

[ai]
binding = "AI"

[[services]]
binding = "BERTHO_AI_AUDIT"
service = "bertho-ai-audit"

[[services]]
binding = "BERTHO_IMAGE_AI"
service = "bertho-ai-image"

[[services]]
binding = "BERTHO_SEARCH_AI"
service = "bertho-ai-search"

[[services]]
binding = "BERTHO_SANDBOX_AI"
service = "bertho-ai-sandbox"